### ISSUE TITLE
async functions no longer work

### ISSUE THREAD

**Issue by gabrielcsapo** [gabrielcsapo/node-notebook#19]
```
TypeError: Identifier 'run' has already been declared
    at evalmachine.<anonymous>:1:1
    at Object.module.exports._run (/Users/gabrielcsapo/Documents/node-notebook/lib/vm.js:151:51)
    at Object.module.exports.run (/Users/gabrielcsapo/Documents/node-notebook/lib/vm.js:50:19)
    at /Users/gabrielcsapo/Documents/node-notebook/lib/vm.js:68:42
    at ChildProcess.<anonymous> (/Users/gabrielcsapo/Documents/node-notebook/lib/vm.js:36:21)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
```

**Comment by derhuerst** [comment]
Hey!

I'm interested in what is best for async functions (combined with the `vm` module), as I need it for [`inspect-code`](https://github.com/derhuerst/inspect-code) and ultimately for [`js-playgrounds`](https://github.com/derhuerst/js-playgrounds).

**Comment by gabrielcsapo** [comment]
Hey @derhuerst I was using babel to get the AST for es7 compliant code, I need to look back into that. 

On other projects I have been using babel and it seems to work well enough. The vm module runs functions top down so It doesn't work well with callback...

The stage-0 babel config does contain the async and await keyword parsing.

**Comment by derhuerst** [comment]
But how did you actually circumvent the async problem?

**Comment by derhuerst** [comment]
Also, see [`vm2`](https://github.com/patriksimek/vm2#vm2---). They seem to have put a lot of thoughts into making a secure vm.

**Comment by gabrielcsapo** [comment]
I might transfer over to vm2. Right now async code does not run 😔 @derhuerst
